export const SOCKET = {
    URL: 'http://localhost:3001',
    EVENTS: {
        CLIENT_SHORT_CODE: 'CLIENT-SHORT_CODE',
        CLIENT_RECEIVED_GAME_REQUEST: 'CLIENT-RECEIVED_GAME_REQUEST',
        CLIENT_GAME_CREATED: 'CLIENT-GAME_CREATED',
        CLIENT_GAME_MOVE: 'CLIENT-GAME_MOVE',

        SERVER_SEND_GAME_REQUEST: 'SERVER-SEND_GAME_REQUEST',
        SERVER_REQUEST_ACCEPTED: 'SERVER-REQUEST_ACCEPTED',
        SERVER_REQUEST_DECLINED: 'SERVER-REQUEST_DECLINED',
        SERVER_GAME_MOVE: 'SERVER-GAME_MOVE',
    }
};


